//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesDB
    {
        public int EmpID { get; set; }
        public string FullName { get; set; }
        public System.DateTime Birthdate { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime DateHired { get; set; }
        public System.Guid Guid { get; set; }
        public bool IsValid { get; set; }
        public string PrintIfValid { get; set; }
    }
}
