//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Dataset class containing properties of each employee in the database.
    /// </summary>
    public partial class EmployeesDB
    {
        /// <summary>
        /// Gets or sets a databise identifier for the employee.
        /// </summary>
        public int EmpID { get; set; }
        /// <summary>
        /// Gets or sets the full name of the employee.
        /// </summary>
        public string FullName { get; set; }
        /// <summary>
        /// Gets or sets the birthdate of the employee.
        /// </summary>
        public System.DateTime Birthdate { get; set; }
        /// <summary>
        ///  Gets or sets the salary of the employee.
        /// </summary>
        public decimal Salary { get; set; }
        /// <summary>
        /// Gets or sets the hire date of the employee.
        /// </summary>
        public System.DateTime DateHired { get; set; }
        /// <summary>
        /// Gets or sets a global unique identifier for the employee.
        /// </summary>
        public System.Guid Guid { get; set; }
        /// <summary>
        /// Gets or sets a boolean that says whether or not the data is valid.
        /// </summary>
        public bool IsValid { get; set; }
        /// <summary>
        /// Gets or sets a string to be printed that tells the user whether or not the data is valid.
        /// </summary>
        public string PrintIfValid { get; set; }
    }
}
